### ISSUE TITLE
Question: Could there be a code along window with this video?

### ISSUE THREAD

**Issue by caraerskine** [learn-co-curriculum/phase-1-lecture-videos-javascript-conditionals#1]
This would have been awesome to have a place to follow along and code. I tried to open a repl and follow along and do it, but it was too hard to juggle windows on a small laptop and have visibility to both. Would there be a way to have a repl kind of built into this page so one could code along with her? JS actually made a ton of sense to me for the first time! Just a thought. And if I am totally missing something obvious sorry!

**Comment by lizbur10** [comment]
Hi @caraerskine! Thanks for the suggestion! There is a tool called Scrimba that allows exactly that! You will see that some of the videos in the curriculum do use that tool. We are making our way through the videos to hopefully update them all to Scrimba, but it will take a little time to get to all of them. 

Thanks for contributing to the Flatiron School curriculum!
